package visual;

import java.util.Date;
import javax.swing.JOptionPane;
import model.Emprestimo;

public class frmCadastroEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form frmCadastroEmprestimo
     */
    public frmCadastroEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents                    
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JBCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBCadastrar = new javax.swing.JButton();
        JCALENDARAQUI = new com.toedter.calendar.JDateChooser();
        JCALENDARDEVO = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        JTFFerramenta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTFAmigo = new javax.swing.JTextField();

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("Cadastro Ferramenta");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setText("Cadastrar Emprestimo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 0, 330, 80);

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCancelar);
        JBCancelar.setBounds(210, 260, 100, 27);

        jLabel5.setText("Data de Devolução:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 180, 120, 16);

        jLabel2.setText("Data de Aquisição:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 120, 140, 16);

        JBCadastrar.setText("Cadastrar");
        JBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCadastrar);
        JBCadastrar.setBounds(30, 260, 100, 27);
        getContentPane().add(JCALENDARAQUI);
        JCALENDARAQUI.setBounds(200, 140, 137, 26);
        getContentPane().add(JCALENDARDEVO);
        JCALENDARDEVO.setBounds(200, 200, 137, 26);

        jLabel1.setText("Ferramenta:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 120, 100, 16);

        JTFFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFFerramentaActionPerformed(evt);
            }
        });
        getContentPane().add(JTFFerramenta);
        JTFFerramenta.setBounds(20, 140, 130, 26);

        jLabel6.setText("Amigo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 80, 16);
        getContentPane().add(JTFAmigo);
        JTFAmigo.setBounds(20, 200, 130, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents                    

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                           
      
        this.dispose();
    }                                          

    private void JBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {                                            
try {
            Date dataAquisicao = JCALENDARAQUI.getDate();
            Date dataDevolucao = JCALENDARDEVO.getDate();
            if (dataAquisicao == null) {
                throw new Exception("Data de Aquisição deve ser preenchida.");
            }
            if (dataDevolucao == null) {
                throw new Exception("Data de Devolução deve ser preenchida.");
            }

           Emprestimo novoEmprestimo = new Emprestimo("Martelo", "Jo\u00e3o", dataAquisicao, dataDevolucao, "Em andamento");
            JOptionPane.showMessageDialog(null, "Empréstimo cadastrado com sucesso!");
            // Optionally clear the date pickers after successful registration
            JCALENDARAQUI.setDate(null);
            JCALENDARDEVO.setDate(null);
            // Print to console (for debugging purposes)
            System.out.println(novoEmprestimo.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }                                           

    private void JTFFerramentaActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmCadastroEmprestimo().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton JBCadastrar;
    private javax.swing.JButton JBCancelar;
    private com.toedter.calendar.JDateChooser JCALENDARAQUI;
    private com.toedter.calendar.JDateChooser JCALENDARDEVO;
    private javax.swing.JTextField JTFAmigo;
    private javax.swing.JTextField JTFFerramenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration                   
}
