package visual;

import javax.swing.JOptionPane;
import model.Emprestimo;
import dao.EmprestimoDAOimpl;
import java.util.Date;

/**
 *
 * @author legen
 */
public class frmCadastroEmprestimo extends javax.swing.JFrame {
 
    private final Emprestimo objetoEmprestimo;
    private final EmprestimoDAOimpl emprestimoDAO;
    /**
     * Creates new form frmCadastroEmprestimos
     */
  public frmCadastroEmprestimo (){
        initComponents();
        this.objetoEmprestimo = new Emprestimo();
        this.emprestimoDAO = new EmprestimoDAOimpl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JBCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JBCadastrar = new javax.swing.JButton();
        JTFDataEmprestimo = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        JTFNomeFerramenta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTFNomeAmigo = new javax.swing.JTextField();

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("Cadastro Ferramenta");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setText("Cadastrar Emprestimo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 0, 330, 80);

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCancelar);
        JBCancelar.setBounds(210, 260, 100, 27);

        jLabel2.setText("Data de Aquisição:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 120, 140, 16);

        JBCadastrar.setText("Cadastrar");
        JBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCadastrar);
        JBCadastrar.setBounds(30, 260, 100, 27);
        getContentPane().add(JTFDataEmprestimo);
        JTFDataEmprestimo.setBounds(200, 140, 137, 26);

        jLabel1.setText("Ferramenta:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 120, 100, 16);

        JTFNomeFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNomeFerramentaActionPerformed(evt);
            }
        });
        getContentPane().add(JTFNomeFerramenta);
        JTFNomeFerramenta.setBounds(20, 140, 130, 26);

        jLabel6.setText("Amigo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 80, 16);
        getContentPane().add(JTFNomeAmigo);
        JTFNomeAmigo.setBounds(20, 200, 130, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
      
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCadastrarActionPerformed
try {
    String nome_amigo = "";
    String nome_ferramenta = "";
    Date dataEmprestimo = null;

    if (this.JTFNomeAmigo.getText().length() < 2) {
        throw new Mensagem("Nome do amigo deve conter ao menos 2 caracteres.");
    } else {
        nome_amigo = this.JTFNomeAmigo.getText();
    }

    if (this.JTFNomeFerramenta.getText().length() < 2) {
        throw new Mensagem("Nome da ferramenta deve conter ao menos 2 caracteres.");
    } else {
        nome_ferramenta = this.JTFNomeFerramenta.getText();
    }

    // Observe que aqui você precisa converter o texto da data para um objeto Date
    // dependendo do formato que você está usando. Vou presumir que você está usando um JDateChooser.
    if (this.JTFDataEmprestimo.getDate() == null) {
        throw new Mensagem("Selecione uma data de empréstimo válida.");
    } else {
        dataEmprestimo = this.JTFDataEmprestimo.getDate();
    }

    // Cria um novo objeto Emprestimo e define seus atributos
    Emprestimo novoEmprestimo = new Emprestimo();
    novoEmprestimo.setNomeAmigo(nome_amigo);
    novoEmprestimo.setNomeFerramenta(nome_ferramenta);
    novoEmprestimo.setDataEmprestimo(dataEmprestimo);

    EmprestimoDAOimpl emprestimoDAO = new EmprestimoDAOimpl();
    boolean inserido = emprestimoDAO.inserirEmprestimoBD(novoEmprestimo);

    if (inserido) {
        JOptionPane.showMessageDialog(null, "Empréstimo cadastrado com sucesso!");
        // Limpa campos da interface
        this.JTFNomeAmigo.setText("");
        this.JTFNomeFerramenta.setText("");
        this.JTFDataEmprestimo.setDate(null); // Limpa a data
    } else {
        JOptionPane.showMessageDialog(null, "Erro ao cadastrar empréstimo.");
    }
    // Exibindo no console o empréstimo cadastrado
    System.out.println(novoEmprestimo.getMinhaLista().toString());
} catch (Mensagem erro) {
    JOptionPane.showMessageDialog(null, erro.getMessage());
} catch (NumberFormatException erro2) {
    JOptionPane.showMessageDialog(null, "Informe um número válido.");
        }
    }//GEN-LAST:event_JBCadastrarActionPerformed

    private void JTFNomeFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNomeFerramentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNomeFerramentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmCadastroEmprestimo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCadastrar;
    private javax.swing.JButton JBCancelar;
    private com.toedter.calendar.JDateChooser JTFDataEmprestimo;
    private javax.swing.JTextField JTFNomeAmigo;
    private javax.swing.JTextField JTFNomeFerramenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
