package visual;

import model.Ferramenta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public final class frmGerenciaFerramenta extends javax.swing.JFrame {

    private final Ferramenta objetoferramenta;

    public frmGerenciaFerramenta() {
        initComponents();
        this.objetoferramenta = new Ferramenta();
        this.carregaTabela();
        
    }

    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTableFerramentas.getModel();
        modelo.setNumRows(0); // Limpa a tabela

        // Carrega a lista de ferramentas
        ArrayList<Ferramenta> listaFerramentas = objetoferramenta.getListaFerramenta();

        // Percorre a lista de ferramentas e adiciona na tabela
        for (Ferramenta ferramenta : listaFerramentas) {
            modelo.addRow(new Object[]{
                ferramenta.getId(),
                ferramenta.getNome(),
                ferramenta.getMarca(),
                ferramenta.getCusto()
                    });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        JBAlterar = new javax.swing.JButton();
        JBApagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JTFNomeTab = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTFMarcaTab = new javax.swing.JTextField();
        JTFCustoTab = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFerramentas = new javax.swing.JTable();
        JBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("Gerenciamento Ferramenta");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 330, 80);

        JBAlterar.setText("Alterar");
        JBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(JBAlterar);
        JBAlterar.setBounds(520, 80, 76, 27);

        JBApagar.setText("Apagar");
        JBApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBApagarActionPerformed(evt);
            }
        });
        getContentPane().add(JBApagar);
        JBApagar.setBounds(610, 80, 76, 27);

        jLabel2.setText("Marca:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 170, 140, 16);
        getContentPane().add(JTFNomeTab);
        JTFNomeTab.setBounds(520, 140, 130, 26);

        jLabel4.setText("Ferramenta:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 120, 140, 20);
        getContentPane().add(JTFMarcaTab);
        JTFMarcaTab.setBounds(520, 190, 130, 26);
        getContentPane().add(JTFCustoTab);
        JTFCustoTab.setBounds(520, 240, 130, 26);

        jLabel6.setText("Custo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 220, 150, 16);

        jTableFerramentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Ferramenta", "Marca", "Custo"
            }
        ));
        jTableFerramentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFerramentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFerramentas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(16, 86, 456, 330);

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCancelar);
        JBCancelar.setBounds(520, 280, 80, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAlterarActionPerformed
        try {
            // Recebendo e validando dados da interface gráfica.
            int id = 0;
            String nome = "";
            String marca = "";
            double custo = 0.0;

            if (this.JTFNomeTab.getText().length() < 2) {
                throw new Mensagem("Nome deve conter ao menos 2 caracteres.");
            } else {
                nome = this.JTFNomeTab.getText();
            }

            if (this.JTFMarcaTab.getText().length() < 2) {
                throw new Mensagem("Marca deve conter ao menos 2 caracteres.");
            } else {
                marca = this.JTFMarcaTab.getText();
            }

            try {
                custo = Double.parseDouble(this.JTFCustoTab.getText());
            } catch (NumberFormatException erro2) {
                throw new Mensagem("Informe um custo válido.");
            }

            if (this.jTableFerramentas.getSelectedRow() == -1) {
                throw new Mensagem("Primeiro selecione uma ferramenta para alterar.");
            } else {
                id = Integer.parseInt(this.jTableFerramentas.getValueAt(this.jTableFerramentas.getSelectedRow(), 0).toString());
            }

            // Envia os dados para o Ferramenta processar
            if (this.objetoferramenta.atualizarFerramenta(id, nome, marca, custo)) {
                // Limpa os campos
                this.JTFNomeTab.setText("");
                this.JTFMarcaTab.setText("");
                this.JTFCustoTab.setText("");
                // JOptionPane.showMessageDialog(rootPane, "Ferramenta alterada com sucesso!");
            }

            // Exibe no console as ferramentas cadastradas
            //System.out.println(this.objetoferramenta.getMinhaLista().toString());
        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // Atualiza a tabela
            carregaTabela();
        }
    }//GEN-LAST:event_JBAlterarActionPerformed

    private void JBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBApagarActionPerformed
         
        int selectedRow = jTableFerramentas.getSelectedRow();
        if (selectedRow >= 0) {
            int ferramentaId = (int) jTableFerramentas.getValueAt(selectedRow, 0);

            int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir esta ferramenta?", "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION);
            if (confirmacao == JOptionPane.YES_OPTION) {
                boolean sucesso = objetoferramenta.deletarFerramenta(ferramentaId);
                if (sucesso) {
                    this.carregaTabela();
                    JOptionPane.showMessageDialog(this, "Ferramenta removida com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao remover a ferramenta.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma ferramenta para remover.");
        }
    }//GEN-LAST:event_JBApagarActionPerformed

    private void jTableFerramentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFerramentasMouseClicked

       if (this.jTableFerramentas.getSelectedRow() != -1) {
    String nome = this.jTableFerramentas.getValueAt(this.jTableFerramentas.getSelectedRow(), 1).toString();
    String marca = this.jTableFerramentas.getValueAt(this.jTableFerramentas.getSelectedRow(), 2).toString();
    String custo = this.jTableFerramentas.getValueAt(this.jTableFerramentas.getSelectedRow(), 3).toString();

    this.JTFNomeTab.setText(nome);
    this.JTFMarcaTab.setText(marca);
    this.JTFCustoTab.setText(custo);
        }
}

    private String getValueFromSelectedRow(int row, int column) {
        Object value = this.jTableFerramentas.getValueAt(row, column);
        return (value != null) ? value.toString() : "";

    }//GEN-LAST:event_jTableFerramentasMouseClicked

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        //Libera todos os recurso da interface gráfica
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(frmGerenciaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(frmGerenciaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(frmGerenciaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(frmGerenciaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGerenciaFerramenta().setVisible(true);
            }
    });
}
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAlterar;
    private javax.swing.JButton JBApagar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JTextField JTFCustoTab;
    private javax.swing.JTextField JTFMarcaTab;
    private javax.swing.JTextField JTFNomeTab;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFerramentas;
    // End of variables declaration//GEN-END:variables

 
    }
