package visual;

import model.Emprestimo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Classe responsável pelo gerenciamento da interface gráfica de empréstimos.
 */
public class frmGerenciaEmprestimo extends javax.swing.JFrame {

    private Emprestimo objetoEmprestimo;
    private SimpleDateFormat dateFormat;

    /**
     * Construtor da classe que inicializa os componentes e carrega a tabela de
     * empréstimos.
     */
    public frmGerenciaEmprestimo() {
        initComponents();
        this.objetoEmprestimo = new Emprestimo();
        this.dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        this.carregaTabela();
    }

    /**
     * Método para carregar a tabela de empréstimos com os dados do banco de
     * dados.
     */
    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.JTableEmprestimo.getModel();
        modelo.setNumRows(0);

        ArrayList<Emprestimo> listaEmprestimos = objetoEmprestimo.getMinhaLista();

        for (Emprestimo emprestimo : listaEmprestimos) {
            modelo.addRow(new Object[]{
                emprestimo.getId(),
                emprestimo.getNomeAmigo(),
                emprestimo.getNomeFerramenta(),
                dateFormat.format(emprestimo.getDataEmprestimo()),
                dateFormat.format(emprestimo.getDataDevolucao()),
                emprestimo.getStatus() ? "Entregue" : "Aberto"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableEmprestimo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jNomeEmprestimo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jNomeFerramenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JBAlterar = new javax.swing.JButton();
        JBApagar = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jDateEmprestimo = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jDateDevolucao = new com.toedter.calendar.JDateChooser();
        JBCancelar = new javax.swing.JButton();
        JStatus = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("Gerenciamento de Empréstimo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, -10, 410, 80);

        JTableEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Amigo", "Ferramenta", "Data do Empréstimo", "Data de Devolução", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTableEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableEmprestimoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableEmprestimo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 720, 330);

        jLabel6.setText("Data Empréstimo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 440, 100, 16);
        getContentPane().add(jNomeEmprestimo);
        jNomeEmprestimo.setBounds(170, 460, 130, 26);

        jLabel4.setText("Amigo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 440, 50, 16);
        getContentPane().add(jNomeFerramenta);
        jNomeFerramenta.setBounds(20, 460, 130, 26);

        jLabel5.setText("Ferramenta:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 440, 70, 20);

        JBAlterar.setText("Alterar");
        JBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(JBAlterar);
        JBAlterar.setBounds(20, 510, 80, 27);

        JBApagar.setText("Apagar");
        JBApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBApagarActionPerformed(evt);
            }
        });
        getContentPane().add(JBApagar);
        JBApagar.setBounds(110, 510, 80, 27);
        getContentPane().add(jCalendar1);
        jCalendar1.setBounds(670, 410, 170, 110);
        getContentPane().add(jDateEmprestimo);
        jDateEmprestimo.setBounds(320, 460, 137, 26);

        jLabel1.setText("Data Devolução:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 440, 90, 16);
        getContentPane().add(jDateDevolucao);
        jDateDevolucao.setBounds(480, 460, 137, 26);

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCancelar);
        JBCancelar.setBounds(200, 510, 80, 27);

        JStatus.setText("Concluído");
        JStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JStatusActionPerformed(evt);
            }
        });
        getContentPane().add(JStatus);
        JStatus.setBounds(490, 500, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método chamado quando uma linha da tabela é clicada. Preenche os campos
     * do formulário com os dados do empréstimo selecionado.
     */
    private void JTableEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableEmprestimoMouseClicked

        if (this.JTableEmprestimo.getSelectedRow() != -1) {
            String nomeAmigo = this.JTableEmprestimo.getValueAt(this.JTableEmprestimo.getSelectedRow(), 1).toString();
            String nomeFerramenta = this.JTableEmprestimo.getValueAt(this.JTableEmprestimo.getSelectedRow(), 2).toString();
            String dataEmprestimoStr = this.JTableEmprestimo.getValueAt(this.JTableEmprestimo.getSelectedRow(), 3).toString();
            String dataDevolucaoStr = this.JTableEmprestimo.getValueAt(this.JTableEmprestimo.getSelectedRow(), 4).toString();
            boolean status = this.JTableEmprestimo.getValueAt(this.JTableEmprestimo.getSelectedRow(), 5).toString().equals("Entregue");

            Date dataEmprestimo = null;
            Date dataDevolucao = null;
            try {
                dataEmprestimo = dateFormat.parse(dataEmprestimoStr);
                dataDevolucao = dateFormat.parse(dataDevolucaoStr);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao formatar datas: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }

            this.jNomeEmprestimo.setText(nomeAmigo);
            this.jNomeFerramenta.setText(nomeFerramenta);
            this.jDateEmprestimo.setDate(dataEmprestimo);
            this.jDateDevolucao.setDate(dataDevolucao);
            this.JStatus.setSelected(status);
        }
    }//GEN-LAST:event_JTableEmprestimoMouseClicked

    /**
     * Método chamado quando o botão "Alterar" é clicado. Atualiza os dados do
     * empréstimo selecionado no banco de dados.
     */
    private void JBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAlterarActionPerformed
        try {
            int id = 0;
            String nomeAmigo = "";
            String nomeFerramenta = "";
            Date dataEmprestimo = null;
            Date dataDevolucao = null;
            boolean status = false;

            if (this.JTableEmprestimo.getSelectedRow() == -1) {
                throw new Mensagem("Primeiro selecione um empréstimo para alterar.");
            } else {
                id = Integer.parseInt(this.JTableEmprestimo.getValueAt(this.JTableEmprestimo.getSelectedRow(), 0).toString());
            }

            nomeAmigo = this.jNomeEmprestimo.getText();
            nomeFerramenta = this.jNomeFerramenta.getText();
            dataEmprestimo = this.jDateEmprestimo.getDate();
            dataDevolucao = this.jDateDevolucao.getDate();
            status = this.JStatus.isSelected(); // Alteração feita aqui

            if (this.objetoEmprestimo.updateEmprestimoBD(id, nomeAmigo, nomeFerramenta, dataEmprestimo, dataDevolucao, status)) {
                this.jNomeEmprestimo.setText("");
                this.jNomeFerramenta.setText("");
                this.jDateEmprestimo.setDate(null);
                this.jDateDevolucao.setDate(null);
                this.JStatus.setSelected(false);
                JOptionPane.showMessageDialog(rootPane, "Empréstimo alterado com sucesso!");
            }

            System.out.println(this.objetoEmprestimo.getMinhaLista().toString());
        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número válido.");
        } finally {
            carregaTabela();

        }
    }//GEN-LAST:event_JBAlterarActionPerformed
    /**
     * Método chamado quando o botão "Apagar" é clicado. Remove o empréstimo
     * selecionado do banco de dados.
     */
    private void JBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBApagarActionPerformed

        try {
            int id = 0;
            if (this.JTableEmprestimo.getSelectedRow() == -1) {
                throw new Mensagem("Primeiro selecione um empréstimo para apagar.");
            } else {
                id = Integer.parseInt(this.JTableEmprestimo.getValueAt(this.JTableEmprestimo.getSelectedRow(), 0).toString());
            }

            int respostaUsuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja apagar este empréstimo?");
            if (respostaUsuario == 0) { // Clicou em SIM
                if (this.objetoEmprestimo.deleteEmprestimoBD(id)) {
                    JOptionPane.showMessageDialog(rootPane, "Empréstimo apagado com sucesso!");
                }
            }

            System.out.println(this.objetoEmprestimo.getMinhaLista().toString());
        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            carregaTabela();

        }
    }//GEN-LAST:event_JBApagarActionPerformed
    /**
     * Método chamado quando o botão "Cancelar" é clicado. Fecha o formulário.
     */
    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    /**
     * Método chamado quando a checkbox de status é clicada. Atualiza o status
     * do empréstimo selecionado.
     */
    private void JStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JStatusActionPerformed
        // TODO add your handling code here:
        int selectedRow = JTableEmprestimo.getSelectedRow();
        if (selectedRow != -1) {
            String status = JStatus.isSelected() ? "Entregue" : "Aberto";
            JTableEmprestimo.setValueAt(status, selectedRow, 6); // Atualiza a célula na coluna de status
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um empréstimo na tabela.");
    }//GEN-LAST:event_JStatusActionPerformed

    }

    /**
     * Método principal para executar a aplicação.
     */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new frmGerenciaEmprestimo().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAlterar;
    private javax.swing.JButton JBApagar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JCheckBox JStatus;
    private javax.swing.JTable JTableEmprestimo;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateDevolucao;
    private com.toedter.calendar.JDateChooser jDateEmprestimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNomeEmprestimo;
    private javax.swing.JTextField jNomeFerramenta;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
