package visual;

public class frmMenuPrincipal extends javax.swing.JFrame {

    public frmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents             
    private void initComponents() {

        JBAMG = new javax.swing.JButton();
        JBGRAMG = new javax.swing.JButton();
        JBGREMP = new javax.swing.JButton();
        JBGRFRM = new javax.swing.JButton();
        JBFRM = new javax.swing.JButton();
        JBEMP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(null);

        JBAMG.setBackground(new java.awt.Color(102, 102, 102));
        JBAMG.setText("Cadastrar Amigo");
        JBAMG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBAMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAMGActionPerformed(evt);
            }
        });
        getContentPane().add(JBAMG);
        JBAMG.setBounds(150, 160, 200, 30);

        JBGRAMG.setBackground(new java.awt.Color(102, 102, 102));
        JBGRAMG.setText("Gerenciar Amigo");
        JBGRAMG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBGRAMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGRAMGActionPerformed(evt);
            }
        });
        getContentPane().add(JBGRAMG);
        JBGRAMG.setBounds(520, 160, 200, 30);

        JBGREMP.setBackground(new java.awt.Color(102, 102, 102));
        JBGREMP.setText("Gerenciar Emprestimo");
        JBGREMP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBGREMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGREMPActionPerformed(evt);
            }
        });
        getContentPane().add(JBGREMP);
        JBGREMP.setBounds(520, 340, 200, 30);

        JBGRFRM.setBackground(new java.awt.Color(102, 102, 102));
        JBGRFRM.setText("Gerenciar Ferramenta");
        JBGRFRM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBGRFRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGRFRMActionPerformed(evt);
            }
        });
        getContentPane().add(JBGRFRM);
        JBGRFRM.setBounds(520, 250, 200, 30);

        JBFRM.setBackground(new java.awt.Color(102, 102, 102));
        JBFRM.setText("Cadastrar Ferramenta");
        JBFRM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBFRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFRMActionPerformed(evt);
            }
        });
        getContentPane().add(JBFRM);
        JBFRM.setBounds(150, 250, 200, 30);

        JBEMP.setBackground(new java.awt.Color(102, 102, 102));
        JBEMP.setText("Cadastrar Emprestimo");
        JBEMP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBEMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEMPActionPerformed(evt);
            }
        });
        getContentPane().add(JBEMP);
        JBEMP.setBounds(150, 340, 200, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("Sistema de Empréstimo de Ferramenta");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 20, 490, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents                  

    private void JBAMGActionPerformed(java.awt.event.ActionEvent evt) {                                      
       frmCadastroAmigo cadamg = new frmCadastroAmigo();
        cadamg.setVisible(true);
    }                                     

    private void JBGRAMGActionPerformed(java.awt.event.ActionEvent evt) {                                        
       frmGerenciaAmigo geramg = new frmGerenciaAmigo();
        geramg.setVisible(true);
    }                                       

    private void JBGREMPActionPerformed(java.awt.event.ActionEvent evt) {                                        
        frmGerenciaEmprestimo gerEmprestimos = new frmGerenciaEmprestimo();
        gerEmprestimos.setVisible(true);
    }                                       

    private void JBGRFRMActionPerformed(java.awt.event.ActionEvent evt) {                                        
          frmGerenciaFerramenta gerFerramentas = new frmGerenciaFerramenta();
        gerFerramentas.setVisible(true);
    }                                       

    private void JBFRMActionPerformed(java.awt.event.ActionEvent evt) {                                      
       frmCadastroFerramenta cadfer = new frmCadastroFerramenta();
        cadfer.setVisible(true);
    }                                     

    private void JBEMPActionPerformed(java.awt.event.ActionEvent evt) {                                      
       frmCadastroEmprestimo cademp = new frmCadastroEmprestimo();
        cademp.setVisible(true);
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
                }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton JBAMG;
    private javax.swing.JButton JBEMP;
    private javax.swing.JButton JBFRM;
    private javax.swing.JButton JBGRAMG;
    private javax.swing.JButton JBGREMP;
    private javax.swing.JButton JBGRFRM;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration                   
}
