/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

/**
 *
 * @author Asus
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBAMG = new javax.swing.JButton();
        JBGRAMG = new javax.swing.JButton();
        JBEMP = new javax.swing.JButton();
        JBGRFRM = new javax.swing.JButton();
        JBFRM = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        JBAMG.setBackground(new java.awt.Color(102, 102, 102));
        JBAMG.setText("Cadastrar Amigo");
        JBAMG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBAMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAMGActionPerformed(evt);
            }
        });
        getContentPane().add(JBAMG);
        JBAMG.setBounds(150, 180, 200, 30);

        JBGRAMG.setBackground(new java.awt.Color(102, 102, 102));
        JBGRAMG.setText("Gerenciar Amigo");
        JBGRAMG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBGRAMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGRAMGActionPerformed(evt);
            }
        });
        getContentPane().add(JBGRAMG);
        JBGRAMG.setBounds(520, 170, 200, 30);

        JBEMP.setBackground(new java.awt.Color(102, 102, 102));
        JBEMP.setText("Gerenciar Emprestimo");
        JBEMP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBEMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEMPActionPerformed(evt);
            }
        });
        getContentPane().add(JBEMP);
        JBEMP.setBounds(520, 350, 200, 30);

        JBGRFRM.setBackground(new java.awt.Color(102, 102, 102));
        JBGRFRM.setText("Gerenciar Ferramenta");
        JBGRFRM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBGRFRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGRFRMActionPerformed(evt);
            }
        });
        getContentPane().add(JBGRFRM);
        JBGRFRM.setBounds(520, 260, 200, 30);

        JBFRM.setBackground(new java.awt.Color(102, 102, 102));
        JBFRM.setText("Cadastrar Ferramenta");
        JBFRM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBFRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFRMActionPerformed(evt);
            }
        });
        getContentPane().add(JBFRM);
        JBFRM.setBounds(150, 260, 200, 30);

        jButton10.setText("jButton1");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(150, 350, 200, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("Sistema de Empréstimo de Ferramenta");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 20, 490, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/menuprincipal.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAMGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBAMGActionPerformed

    private void JBGRAMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGRAMGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBGRAMGActionPerformed

    private void JBEMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBEMPActionPerformed

    private void JBGRFRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGRFRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBGRFRMActionPerformed

    private void JBFRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBFRMActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAMG;
    private javax.swing.JButton JBEMP;
    private javax.swing.JButton JBFRM;
    private javax.swing.JButton JBGRAMG;
    private javax.swing.JButton JBGRFRM;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
